# Generated by Django 3.2.20 on 2023-08-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230815_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_minutes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
