# Generated by Django 3.2.20 on 2023-08-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
