#config for github actions
--- #--- specify that this is a yml file
#name for file
name: checks

#trigger actions
on: [push]

jobs:
  test-lint: #test ID
    name: Test and Lint #human friendly name
    runs-on: ubuntu-20.04 #runner on which job will run. It is the OS on which we will run the job. Windows runner might cost some more.  Docker comes preinstalled on this runner
    steps:
    #step 1: logs into docker hub
      - name: Login to Docker Hub #human friendly name
        uses: docker/login-action@v1 #premade actions in github, helps utilise them
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    #step 2: checks out using checkout action
      - name: Checkout
        uses: actions/checkout@v2
    # step 3,4: run test and linting using docker compose
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
    # if any of these steps fail, we come with return other than exit 0, indicating faliure.


